
SELECT 
    clientes.IDENTIFICACI�N, 
    clientes.nombre,
    clientes.TIPO_DOCUMENTO,
    clientes.CLASIFICACION,
    clientes.TIPO_TARJETA,
    clientes.FECHA_APERTURA_TARJETA,
    clientes.ESTADO_TARJETA,
    CATEGORIAS_CONSUMO.NOMBRE_CATEGORIA,
    COUNT(TRANSACCIONES.ID_TRANSACCION) AS Total_Transacciones,  
    MAX(TRANSACCIONES.FECHA_TRANSACCION) AS Ultima_transacci�n
FROM 
    TRANSACCIONES 
LEFT JOIN  CLIENTES ON CLIENTES.IDENTIFICACI�N = TRANSACCIONES.IDENTIFICACION 
LEFT JOIN 
    CATEGORIAS_CONSUMO ON TRANSACCIONES.CODIGO_CATEGORIA = CATEGORIAS_CONSUMO.CODIGO_CATEGORIA 
GROUP BY 
    CLIENTES.IDENTIFICACI�N,
    CLIENTES.nombre,
    CLIENTES.TIPO_DOCUMENTO,
    CLIENTES.CLASIFICACION,
    CLIENTES.TIPO_TARJETA,
    CLIENTES.FECHA_APERTURA_TARJETA,
    CLIENTES.ESTADO_TARJETA,
    CATEGORIAS_CONSUMO.NOMBRE_CATEGORIA
;



WITH CategoriaPreferida AS (
    SELECT 
        clientes.IDENTIFICACI�N, 
        clientes.nombre,
        clientes.TIPO_DOCUMENTO,
        clientes.CLASIFICACION,
        clientes.TIPO_TARJETA,
        clientes.FECHA_APERTURA_TARJETA,
        clientes.ESTADO_TARJETA,
        CATEGORIAS_CONSUMO.NOMBRE_CATEGORIA,
        COUNT(TRANSACCIONES.ID_TRANSACCION) AS Total_Transacciones,
        MAX(TRANSACCIONES.FECHA_TRANSACCION) AS Ultima_transacci�n,  
        ROW_NUMBER() OVER (
            PARTITION BY clientes.IDENTIFICACI�N 
            ORDER BY COUNT(TRANSACCIONES.ID_TRANSACCION) DESC 
        ) AS rango
    FROM 
        TRANSACCIONES 
    LEFT JOIN  CLIENTES ON CLIENTES.IDENTIFICACI�N = TRANSACCIONES.IDENTIFICACION 
    LEFT JOIN 
        CATEGORIAS_CONSUMO ON TRANSACCIONES.CODIGO_CATEGORIA = CATEGORIAS_CONSUMO.CODIGO_CATEGORIA 
    GROUP BY 
        CLIENTES.IDENTIFICACI�N,
        CLIENTES.nombre,
        CLIENTES.TIPO_DOCUMENTO,
        CLIENTES.CLASIFICACION,
        CLIENTES.TIPO_TARJETA,
        CLIENTES.FECHA_APERTURA_TARJETA,
        CLIENTES.ESTADO_TARJETA,
        CATEGORIAS_CONSUMO.NOMBRE_CATEGORIA
)

SELECT 
    IDENTIFICACI�N,
    nombre,
    TIPO_DOCUMENTO,
    CLASIFICACION,
    TIPO_TARJETA,
    FECHA_APERTURA_TARJETA,
    ESTADO_TARJETA,
    NOMBRE_CATEGORIA,
    Total_Transacciones,
    Ultima_transacci�n  
FROM 
    CategoriaPreferida
WHERE 
    rango = 1  
ORDER BY 
    Total_Transacciones desc;
